// import React from "react";
// import Products from "../pages/Products";
// import family from "../public/family-slide.jpg";

// const filters = [];
// const products = [
//     {
//       id: 1,
//       name: "User 1",
//       title: "Classic Crewneck",
//       ownerName: "Alice",
//       phone: "1234567890",
//       country: "India",
//       state: "Telangana",
//       mandal: "Mandal A",
//       region: "North",
//       category: "Tees",
//       imageSrc: family,
//       imageAlt: "Crewneck",
//       price: "$35",
//     },
//     {
//       id: 2,
//       name: "User 2",
//       title: "Premium Hoodie",
//       ownerName: "Bob",
//       phone: "9876543210",
//       country: "India",
//       state: "Andhra Pradesh",
//       mandal: "Mandal B",
//       region: "South",
//       category: "Sweatshirts",
//       imageSrc: family,
//       imageAlt: "Hoodie",
//       price: "$40",
//     },
//     {
//       id: 3,
//       name: "User 3",
//       title: "Comfort Tee",
//       ownerName: "Charlie",
//       phone: "1112223333",
//       country: "USA",
//       state: "California",
//       mandal: "Mandal C",
//       region: "West",
//       category: "Tees",
//       imageSrc: family,
//       imageAlt: "Tee",
//       price: "$30",
//     },
//     {
//         id: 4,
//         name: "User 3",
//         title: "Comfort Tee",
//         ownerName: "Charlie",
//         phone: "1112223333",
//         country: "USA",
//         state: "California",
//         mandal: "Mandal C",
//         region: "West",
//         category: "Tees",
//         imageSrc: family,
//         imageAlt: "Tee",
//         price: "$30",
//       },
//       {
//         id: 5,
//         name: "User 3",
//         title: "Comfort Tee",
//         ownerName: "Charlie",
//         phone: "1112223333",
//         country: "Japan",
//         state: "California",
//         mandal: "Mandal C",
//         region: "West",
//         category: "Tees",
//         imageSrc: family,
//         imageAlt: "Tee",
//         price: "$30",
//       },
//       {
//         id: 6,
//         name: "User 3",
//         title: "Comfort Tee",
//         ownerName: "Charlie",
//         phone: "1112223333",
//         country: "USA",
//         state: "California",
//         mandal: "Mandal C",
//         region: "West",
//         category: "Tees",
//         imageSrc: family,
//         imageAlt: "Tee",
//         price: "$30",
//       },
//       {
//         id: 7,
//         name: "User 3",
//         title: "Comfort Tee",
//         ownerName: "Charlie",
//         phone: "1112223333",
//         country: "China",
//         state: "California",
//         mandal: "Mandal C",
//         region: "West",
//         category: "Tees",
//         imageSrc: family,
//         imageAlt: "Tee",
//         price: "$30",
//       },
//   ];

// function Filter() {
//   return (
//     <div>
//       {/* <Products products={products} filterData={filterData} />*/}
//       <Products products={products} filters={filters} />
//     </div>
//   );
// }

// export default Filter;



import React from "react";
import Products from "../pages/Products";
import family from "../public/family-slide.jpg";

const filters = [];

const products = [
  {
    id: 1,
    name: "DSR Swamy",
    title: "Vasavi Temple",
    ownerName: "DSR Swamy",
    phone: "9390980737",
    country: "India",
    state: "Andhra Pradesh",
    district: "Prakasham",
    city: "North",
    category: "Temple",
    templeName: "Pulivendala",
    imageSrc: family,
    imageAlt: "Temple",
    price: "$0",
  },
  {
    id: 2,
    name: "Kaluva Basker",
    title: "AIV Sangham",
    ownerName: "Kaluva Basker",
    phone: "9492711530",
    country: "India",
    state: "Andhra Pradesh",
    district: "Mandal F",
    city: "East",
    category: "Sangham",
    templeName: "Chittoor",
    imageSrc: family,
    imageAlt: "AIV Sangham",
    price: "$0",
  },
  {
    id: 3,
    name: "Sure Umadevi",
    title: "Mahila A.V.S",
    ownerName: "Sure Umadevi",
    phone: "9160692526",
    country: "India",
    state: "Andhra Pradesh",
    district: "Mandal E",
    city: "West",
    category: "Women Services",
    templeName: "Chapara",
    imageSrc: family,
    imageAlt: "Mahila AVS",
    price: "$0",
  },
  {
    id: 4,
    name: "Gajulapalli Prasad",
    title: "Vasavi Clubs",
    ownerName: "Gajulapalli Prasad",
    phone: "8297908645",
    country: "India",
    state: "Andhra Pradesh",
    district: "Mandal D",
    city: "Markapur",
    category: "Clubs",
    templeName: "Badvel",
    imageSrc: family,
    imageAlt: "Vasavi Clubs",
    price: "$0",
  },
  {
    id: 5,
    name: "Gontla Krishna",
    title: "Vasavi Sevadal ex-District President",
    ownerName: "Gontla Krishna",
    phone: "9247112777",
    country: "India",
    state: "Andhra Pradesh",
    district: "Mandal C",
    city: "South",
    category: "Social Service",
    templeName: "Chittoor",
    imageSrc: family,
    imageAlt: "Sevadal",
    price: "$0",
  },
  {
    id: 6,
    name: "Devisetty Ramashekar",
    title: "AVOPA, AP State Committee",
    ownerName: "Devisetty Ramashekar",
    phone: "9440277913",
    country: "India",
    state: "Andhra Pradesh",
    district: "Prakasham",
    city: "Markapur",
    category: "Temple",
    templeName: "Pulivendala",
    imageSrc: family,
    imageAlt: "AVOPA",
    price: "$0",
  },
  {
    id: 7,
    name: "Yelamanchili Subbarao",
    title: "Voters, Press - Prajabhoomi",
    ownerName: "Yelamanchili Subbarao",
    phone: "6301508172",
    country: "India",
    state: "Andhra Pradesh",
    district: "Prakasham",
    city: "Markapur",
    category: "Media",
    templeName: "Badvel",
    imageSrc: family,
    imageAlt: "Prajabhoomi",
    price: "$0",
  },
  {
    id: 8,
    name: "Vutukuri Madhava Rao",
    title: "Chamber of Commerce, ex-president",
    ownerName: "Vutukuri Madhava Rao",
    phone: "",
    country: "India",
    state: "Andhra Pradesh",
    district: "Chapara",
    city: "Markapur",
    category: "Temple",
    templeName: "Badvel",
    imageSrc: family,
    imageAlt: "Chamber of Commerce",
    price: "$0",
  },
  {
    id: 9,
    name: "Tadikamalla Shiva Krishna",
    title: "Journalist, OnGillenews",
    ownerName: "Tadikamalla Shiva Krishna",
    phone: "8281798511",
    country: "USA",
    state: "Andhra Pradesh",
    district: "Prakasham",
    city: "Markapur", 
    category: "Temple",
    templeName: "Chittoor",
    imageSrc: family,
    imageAlt: "OnGillenews",
    price: "$0",
  },
  {
    id: 10,
    name: "G.L. Prasad Gupta",
    title: "Export, Slate Export",
    ownerName: "G.L. Prasad Gupta",
    phone: "9440265857",
    country: "India",
    state: "Andhra Pradesh",
    district: "Unknown",
    city: "South",
    category: "Export",
    templeName: "Pulivendala",
    imageSrc: family,
    imageAlt: "Slate Export",
    price: "$0",
  },
];

function Filter() {
  return (
    <div>
      <Products products={products} filters={filters} />
    </div>
  );
}

export default Filter;
